"""Initial migration

Revision ID: c9d85687d00b
Revises: 
Create Date: 2025-08-02 21:57:11.807367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9d85687d00b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('court', sa.String(length=100), nullable=False),
    sa.Column('case_type', sa.String(length=100), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('filing_year', sa.Integer(), nullable=False),
    sa.Column('parties', sa.Text(), nullable=True),
    sa.Column('next_hearing_date', sa.Date(), nullable=True),
    sa.Column('judgment_pdf_link', sa.String(length=255), nullable=True),
    sa.Column('filing_date', sa.Date(), nullable=True),
    sa.Column('order_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scraping_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scraping_logs')
    op.drop_table('cases')
    # ### end Alembic commands ###
